#!/usr/bin/env php
<?php

namespace Tuncay\PsalmWpTaint;

require_once "./vendor/autoload.php";


use Tuncay\PsalmWpTaint\src\Cli\PsalmWpTaintAnalysis;
use Tuncay\PsalmWpTaint\src\Cli\RunAnalyzeCommand;

$command        = new RunAnalyzeCommand();
$commandCorrect = $command->parseCommand( $argv );

if ( ! $commandCorrect ) {
	exit();
}

PsalmWpTaintAnalysis::run( $command );
