#!/usr/bin/env php
<?php

namespace PsalmWpTaint;

require_once "./vendor/autoload.php";

use AnalyzeCommand;
use PsalmWpTaintAnalysis;

$command = new AnalyzeCommand();
$commandCorrect = $command->parseCommand($argv);

if (!$commandCorrect) exit();

PsalmWpTaintAnalysis::run($command);
